version: 2
updates:
  - package-ecosystem: bun
    directories:
      - /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
