import type { Options } from "../../types";

/** Omitted from the rendered element so engine props never reach the DOM. */
export const OPTION_KEYS = [
  "initial",
  "animate",
  "exit",
  "variants",
  "inherit",
  "style",
  "transition",
  "transformTemplate",
  "custom",
  // layout
  "layout",
  "layoutId",
  "layoutScroll",
  "layoutRoot",
  "layoutDependency",
  "crossfade",
  // gesture animation targets
  "whileHover",
  "whilePress",
  "whileInView",
  "whileFocus",
  "whileDrag",
  "inViewOptions",
  "globalPressTarget",
  // drag
  "drag",
  "dragSnapToOrigin",
  "dragDirectionLock",
  "dragPropagation",
  "dragConstraints",
  "dragElastic",
  "dragMomentum",
  "dragTransition",
  "dragListener",
  "dragControls",
  // engine callbacks (not DOM events)
  "onAnimationStart",
  "onAnimationComplete",
  "onUpdate",
  "onHoverStart",
  "onHoverEnd",
  "onPressStart",
  "onPress",
  "onPressCancel",
  "onViewportEnter",
  "onViewportLeave",
  "onDragStart",
  "onDragEnd",
  "onDrag",
  "onDirectionLock",
  "onDragTransitionEnd",
  "onMeasureDragConstraints",
  "onPanSessionStart",
  "onPanStart",
  "onPan",
  "onPanEnd",
  "onBeforeLayoutMeasure",
  "onLayoutMeasure",
  "onLayoutAnimationStart",
  "onLayoutAnimationComplete",
] as const satisfies ReadonlyArray<keyof Options>;
